#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x6FFC33439B0D04DF (erik.winkels@open-xchange.com)
#
Name     : pdns-recursor
Version  : 4.1.12
Release  : 10
URL      : https://downloads.powerdns.com/releases/pdns-recursor-4.1.12.tar.bz2
Source0  : https://downloads.powerdns.com/releases/pdns-recursor-4.1.12.tar.bz2
Source99 : https://downloads.powerdns.com/releases/pdns-recursor-4.1.12.tar.bz2.asc
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 MIT
Requires: pdns-recursor-bin = %{version}-%{release}
Requires: pdns-recursor-license = %{version}-%{release}
Requires: pdns-recursor-man = %{version}-%{release}
Requires: pdns-recursor-services = %{version}-%{release}
BuildRequires : LuaJIT-dev
BuildRequires : boost-dev
BuildRequires : curl-dev
BuildRequires : openssl-dev
BuildRequires : protobuf-dev
BuildRequires : ragel
BuildRequires : systemd-dev
BuildRequires : valgrind
BuildRequires : virtualenv

%description
PowerDNS Recursor
-----------------
For full details, please read https://doc.powerdns.com/md/recursor/

%package bin
Summary: bin components for the pdns-recursor package.
Group: Binaries
Requires: pdns-recursor-license = %{version}-%{release}
Requires: pdns-recursor-services = %{version}-%{release}

%description bin
bin components for the pdns-recursor package.


%package license
Summary: license components for the pdns-recursor package.
Group: Default

%description license
license components for the pdns-recursor package.


%package man
Summary: man components for the pdns-recursor package.
Group: Default

%description man
man components for the pdns-recursor package.


%package services
Summary: services components for the pdns-recursor package.
Group: Systemd services

%description services
services components for the pdns-recursor package.


%prep
%setup -q -n pdns-recursor-4.1.12

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1554228743
export CFLAGS="-O2 -g -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=32 -Wformat -Wformat-security -Wno-error -Wl,-z,max-page-size=0x1000 -march=westmere -mtune=haswell"
export CXXFLAGS=$CFLAGS
unset LDFLAGS
export LDFLAGS="${LDFLAGS} -fno-lto"
%configure --disable-static --with-luajit \
--enable-reproducible \
--enable-unit-tests \
--enable-valgrind \
--enable-systemd \
--with-socketdir=/run
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1554228743
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pdns-recursor
cp COPYING %{buildroot}/usr/share/package-licenses/pdns-recursor/COPYING
cp NOTICE %{buildroot}/usr/share/package-licenses/pdns-recursor/NOTICE
cp ext/json11/LICENSE.txt %{buildroot}/usr/share/package-licenses/pdns-recursor/ext_json11_LICENSE.txt
cp ext/yahttp/LICENSE %{buildroot}/usr/share/package-licenses/pdns-recursor/ext_yahttp_LICENSE
cp html/LICENSE %{buildroot}/usr/share/package-licenses/pdns-recursor/html_LICENSE
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pdns_recursor
/usr/bin/rec_control

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pdns-recursor/COPYING
/usr/share/package-licenses/pdns-recursor/NOTICE
/usr/share/package-licenses/pdns-recursor/ext_json11_LICENSE.txt
/usr/share/package-licenses/pdns-recursor/ext_yahttp_LICENSE
/usr/share/package-licenses/pdns-recursor/html_LICENSE

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/pdns_recursor.1
/usr/share/man/man1/rec_control.1

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/pdns-recursor.service
/usr/lib/systemd/system/pdns-recursor@.service
